### PR TITLE
Missing translations

### PR DESCRIPTION
**Pull request by tecjam**
all terms translated or copied from english to avoid non-descriptive #NAME? output

### CODE REVIEW

**Comment by niclashoyer** [comment]
thank you! We're currently translating another batch of ~2000 missing English terms. Somehow the command `bin/magento i18n:collect-phrases` does not return all phrases, especially phrases used in the fronted with JavaScript were missing. Once we're ready we'll merge with your changes.

**Comment by niclashoyer** [comment]
@tecjam I'm currently merging your changes into ours, please stand by

**Comment by niclashoyer** [comment]
@tecjam merged in #6 (I rebased your commits). As a next step we'll sort all entries in the CSV, so please update your repository if you do any further modifiactions

**Comment by tecjam** [comment]
@niclashoyer Thank you, I will.

**Pull request closed without merging**
